/*
 * test_srp.c — SRP-6a vectors and the Apple-variant validation harness.
 *
 * Two tiers:
 *  (1) Structural checks that always run (A is in range, deterministic with a
 *      fixed `a`, session key/M1 are produced).
 *  (2) Apple-variant correctness — the exact M1/x/u byte values. These are the
 *      claims that must be pinned against an oracle:
 *        - with -DGSA_DIFF_CORECRYPTO: diff byte-for-byte vs Apple corecrypto.
 *        - otherwise: against a frozen golden vector once captured.
 *      Until a golden/oracle is wired in, tier (2) is reported as SKIPPED so CI
 *      stays honest (green != "SRP proven correct").
 */
#include "gsa/srp.h"
#include "gsa/crypto.h"
#include "test_util.h"
#include "vectors/apple_srp_vector.h"

/* Deterministic: same fixed `a` must yield the same A across runs. */
static void test_srp_deterministic_A(void) {
    uint8_t fixed_a[32];
    for (int i = 0; i < 32; i++) fixed_a[i] = (uint8_t)(i + 1);

    gsa_srp_ctx *c1 = gsa_srp_new();
    gsa_srp_ctx *c2 = gsa_srp_new();
    CHECK_TRUE("srp_new c1", c1 != NULL);
    CHECK_TRUE("srp_new c2", c2 != NULL);
    gsa_srp_set_fixed_a(c1, fixed_a, sizeof(fixed_a));
    gsa_srp_set_fixed_a(c2, fixed_a, sizeof(fixed_a));

    size_t n1 = 0, n2 = 0;
    gsa_srp_start(c1, NULL, &n1);
    gsa_srp_start(c2, NULL, &n2);
    CHECK_TRUE("A width == 256 (2048-bit group)", n1 == 256 && n2 == 256);

    uint8_t A1[256], A2[256];
    size_t l1 = sizeof(A1), l2 = sizeof(A2);
    int r1 = gsa_srp_start(c1, A1, &l1);
    int r2 = gsa_srp_start(c2, A2, &l2);
    CHECK_TRUE("srp_start ok", r1 == 0 && r2 == 0);
    CHECK_EQ_BYTES("fixed-a => deterministic A", A1, A2, 256);

    gsa_srp_free(c1);
    gsa_srp_free(c2);
}

/* s2k vs s2k_fo produce different keys; both are 32 bytes and deterministic. */
static void test_s2k(void) {
    const uint8_t salt[16] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
    uint8_t k_s2k[32], k_s2kfo[32], k_s2k_b[32];
    int a = gsa_srp_s2k("hunter2", salt, sizeof(salt), 1000, 0, k_s2k);
    int b = gsa_srp_s2k("hunter2", salt, sizeof(salt), 1000, 1, k_s2kfo);
    int c = gsa_srp_s2k("hunter2", salt, sizeof(salt), 1000, 0, k_s2k_b);
    CHECK_TRUE("s2k returns 0", a == 0 && b == 0 && c == 0);
    CHECK_EQ_BYTES("s2k deterministic", k_s2k, k_s2k_b, 32);
    CHECK_TRUE("s2k != s2k_fo", memcmp(k_s2k, k_s2kfo, 32) != 0);
}

/*
 * Apple-variant exactness, pinned against a frozen golden vector generated by
 * tests/oracle/gsa_oracle.py using the MIT `srp` library (the same SRP-6a code
 * that authenticates live against Apple GrandSlam). This is where correctness
 * is actually proven: every byte of A, the s2k password key, M1, the session
 * key K, and the server proof M2 must match the oracle exactly.
 */
static void test_apple_variant_exact(void) {
    gsa_srp_ctx *ctx = gsa_srp_new();
    CHECK_TRUE("srp_new (apple vector)", ctx != NULL);
    if (!ctx) return;

    /* A = g^a mod N with the frozen private exponent. */
    int sa = gsa_srp_set_fixed_a(ctx, GSA_VEC_FIXED_A, sizeof(GSA_VEC_FIXED_A));
    CHECK_TRUE("set_fixed_a ok", sa == 0);
    uint8_t A[256];
    size_t Alen = sizeof(A);
    int rs = gsa_srp_start(ctx, A, &Alen);
    CHECK_TRUE("srp_start ok", rs == 0 && Alen == sizeof(GSA_VEC_A));
    CHECK_EQ_BYTES("A == oracle", A, GSA_VEC_A, sizeof(GSA_VEC_A));

    /* s2k password key. */
    uint8_t pwkey[32];
    int rk = gsa_srp_s2k(GSA_VEC_PASSWORD, GSA_VEC_SALT, sizeof(GSA_VEC_SALT),
                         GSA_VEC_ITERATIONS, 0, pwkey);
    CHECK_TRUE("s2k ok", rk == 0);
    CHECK_EQ_BYTES("password_key == oracle", pwkey, GSA_VEC_PWKEY, sizeof(GSA_VEC_PWKEY));

    /* M1 from the challenge. */
    uint8_t m1[32];
    int rp = gsa_srp_process(ctx, GSA_VEC_USERNAME, pwkey, sizeof(pwkey),
                             GSA_VEC_SALT, sizeof(GSA_VEC_SALT),
                             GSA_VEC_FIXED_B, sizeof(GSA_VEC_FIXED_B), m1);
    CHECK_TRUE("srp_process ok", rp == 0);
    CHECK_EQ_BYTES("M1 == oracle", m1, GSA_VEC_M1, sizeof(GSA_VEC_M1));

    /* Session key K = H(S). */
    uint8_t K[32];
    size_t klen = sizeof(K);
    int rkey = gsa_srp_session_key(ctx, K, &klen);
    CHECK_TRUE("session_key ok", rkey == 0 && klen == sizeof(GSA_VEC_K));
    CHECK_EQ_BYTES("K == oracle", K, GSA_VEC_K, sizeof(GSA_VEC_K));

    /* Server proof M2 must verify. */
    int rv = gsa_srp_verify(ctx, GSA_VEC_M2);
    CHECK_TRUE("verify(M2) accepts oracle proof", rv == 0);

    gsa_srp_free(ctx);
}

int main(void) {
    test_srp_deterministic_A();
    test_s2k();
    test_apple_variant_exact();
    return TEST_SUMMARY();
}
